# Run all scripts for consumption inequality
# Author: BoYanHuang
# Created Jun 13, 2025
# Last modify Jun 13, 2025 by BoYanHuang

# Run from the repository root; every path below is relative to it.

# Output directories are not tracked, so a fresh clone has none of them and
# the first ggsave would fail.
for (d in file.path("figures", paste0("Fig_", 1:8))) {
    dir.create(d, recursive = TRUE, showWarnings = FALSE)
}
dir.create("figures/missing", recursive = TRUE, showWarnings = FALSE)
dir.create("HH_inc_exp", recursive = TRUE, showWarnings = FALSE)

# Stage 1: build the harmonized panel from the yearly Stata files.
source("script//equivalization.R")

# Stage 2: the figures that read the panel.
source("script//fig_1-2.R")
source("script//fig_3-5.R")
source("script//fig_6-7.R")

# Figures that read the raw files or the CPI series directly. These were not
# in run_all before, so the missing-rate and CPI figures in the paper could
# only be regenerated by hand.
source("script//missing_val.R")
source("script//additional_plots.R")
